name: Fortify SSC Scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fortify:
    runs-on: windows-2022

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      # Thay đổi build tool phù hợp nếu dự án cần (ví dụ Java/Maven, .NET, Node.js...)
      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # Bước 1: Setup môi trường công cụ Fortify (fcli, scancentral...)
      - name: Setup Fortify Tools
        uses: fortify/github-action@v3
        env:
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_SAST_TOKEN }}
          SSC_APPVERSION: ${{ secrets.SSC_APPVERSION }}
          SSC_APPLICATION: ${{ secrets.SSC_APP }}

      # Bước 2: Chạy lệnh quét ScanCentral
      - name: Run Fortify Scan
        shell: pwsh
        run: |
          scancentral -url "$env:SSC_URL" start -uptoken "$env:SSC_TOKEN" -application "$env:SSC_APPLICATION" -version "$env:SSC_APPVERSION"
        env:
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_SAST_TOKEN }}
          SSC_APPVERSION: ${{ secrets.SSC_APPVERSION }}
          SSC_APPLICATION: ${{ secrets.SSC_APP }}
